# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json


###
# создание объявления token_ 1
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 56c945ecfaac069442ecede01caef19ab2eb8e7d

{
  "title": "finish_test_4_user_1",
  "description": "++++++"
}


### 
# создание объявления token_ 2
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 20cbb5dabe7fa13166be45c8cabebc25b7d14822

{
  "title": "finish_test_6_user_2",
  "description": "++++++"
}


###
# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/9/
Content-Type: application/json
Authorization: Token 56c945ecfaac069442ecede01caef19ab2eb8e7d

{
  "status": "CLOSED"
}


###
#  удалить объявление
DELETE {{baseUrl}}/advertisements/22/
Content-Type: application/json
Authorization: Token 56c945ecfaac069442ecede01caef19ab2eb8e7d


###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json


###
# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###
# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2023-12-10
Content-Type: application/json
