# Generated by Django 3.1.2 on 2023-11-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_auto_20231109_1039"),
    ]

    operations = [
        migrations.AddField(
            model_name="scope",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
