# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "arbuzz",
  "description": "Astrahan arbuz"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/2/
Content-Type: application/json

{
  "description": "Senegal potatos"
}

###

# удаление продукта
DELETE {{baseUrl}}/products//
Content-Type: application/json

###

# поиск продуктов по названию
GET {{baseUrl}}/products/?title=potatos
Content-Type: application/json

###

# поиск продуктов по описанию
GET {{baseUrl}}/products/?search=China 
Content-Type: application/json







###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "petrozavodsk_13",
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/11/
Content-Type: application/json

{
  "positions": [
    {
      "product": 5,
      "quantity": 777,
      "price": 333
    }
  ]
}

###

# поиск складов, где есть определенный продукт (по id)
GET {{baseUrl}}/stocks/?products=4
Content-Type: application/json

###

# поиск складов, где есть определенный продукт (по оптсанию )
GET {{baseUrl}}/stocks/?search=China
Content-Type: application/json




###
# поиск складов, где есть определенный продукт

GET {{baseUrl}}/name_product/?search=China
Content-Type: application/json





