# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "apple",
  "description": "poland"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/1/
Content-Type: application/json

{
  "description": "Fillipin cocos"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###

# поиск продуктов по описанию или описанию
GET {{baseUrl}}/products/?search=pol
Content-Type: application/json


###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "inoin_stock",
  "positions": [
    {
      "product": 14,
      "quantity": 10,
      "price": 150
    },
    {
      "product": 17,
      "quantity": 10,
      "price": 160
    },
    {
      "product": 18,
      "quantity": 1,
      "price": 13000000
    },
    {
      "product": 21,
      "quantity": 3,
      "price": 18000000
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/17/
Content-Type: application/json

{
  "positions": [
    {
      "product": 14,
      "quantity": 8,
      "price": 170
    },
    {
      "product": 22,
      "quantity": 10,
      "price": 190
    }
    
  ]
}

###

# поиск складов, где есть определенный продукт (по id)
GET {{baseUrl}}/stocks/?products=22
Content-Type: application/json

###

# Доп задание
# поиск складов, где есть определенный продукт (по описанию )
GET {{baseUrl}}/stocks/?search=911
Content-Type: application/json








