# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "kiwi",
  "description": "Madagaskar kiwi"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/8/
Content-Type: application/json

{
  "description": "Madagaskar green kiwi"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/8/
Content-Type: application/json

###

# поиск продуктов по названию
GET {{baseUrl}}/products/?title=kiwi
Content-Type: application/json

###

# поиск продуктов по описанию
GET {{baseUrl}}/products/?search=Uzbek 
Content-Type: application/json


###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "petrozavodsk_15",
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/13/
Content-Type: application/json

{
  "positions": [
    {
      "product": 9,
      "quantity": 777,
      "price": 333
    }
  ]
}

###

# поиск складов, где есть определенный продукт (по id)
GET {{baseUrl}}/stocks/?products=5
Content-Type: application/json

###

# Доп задание
# поиск складов, где есть определенный продукт (по описанию )
GET {{baseUrl}}/stocks/?search=kiwi
Content-Type: application/json








